# site settings
title: Stan's IT sharing
email: stan@stanwu.ca
description: > # this means to ignore newlines until "baseurl:"
  覺得文章有幫助 ? 請不吝嗇加入追蹤筆者的 Github 或是 Twitter 
  帳號作為獎勵吧 ! 

# the subpath of your site, e.g. /blog/
baseurl: ""

# the base hostname & protocol for your site
url: "http://stanwu.ca"

# social media
twitter_username: stanwu
github_username:  stanwu

# images source
img_url: "http://stanwu.us"

# build settings
markdown: kramdown

#relate source index
lsi: true

# resource
keep_files: ["downloads", "assets"]