# Site settings
title: Stan's IT sharing
email: stan@stanwu.org
description: > # this means to ignore newlines until "baseurl:"
  覺得文章有幫助 ? 註冊一個 MozyHome 免費帳號, 並完成資料備份, 除了原本 
  2GB 之外, 還可獲得至少 250MB 額外儲存空間 ! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stanwutw.github.io" # the base hostname & protocol for your site
twitter_username: stanwu
github_username:  stanwu

# Build settings
markdown: kramdown
